# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initialize_from_hdf5_sparse <- function(file, name, nrow, ncol, byrow) {
    .Call('_beachmat_hdf5_initialize_from_hdf5_sparse', PACKAGE = 'beachmat.hdf5', file, name, nrow, ncol, byrow)
}

initialize_from_hdf5_dense <- function(file, name) {
    .Call('_beachmat_hdf5_initialize_from_hdf5_dense', PACKAGE = 'beachmat.hdf5', file, name)
}

