# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initialize_from_hdf5_sparse <- function(file, name, nrow, ncol, csr, cache_size) {
    .Call('_beachmat_hdf5_initialize_from_hdf5_sparse', PACKAGE = 'beachmat.hdf5', file, name, nrow, ncol, csr, cache_size)
}

initialize_from_hdf5_dense <- function(file, name, transpose, cache_size) {
    .Call('_beachmat_hdf5_initialize_from_hdf5_dense', PACKAGE = 'beachmat.hdf5', file, name, transpose, cache_size)
}

load_into_memory_sparse <- function(file, name, nrow, ncol, csr, forced_int) {
    .Call('_beachmat_hdf5_load_into_memory_sparse', PACKAGE = 'beachmat.hdf5', file, name, nrow, ncol, csr, forced_int)
}

load_into_memory_dense <- function(file, name, forced_int, transpose) {
    .Call('_beachmat_hdf5_load_into_memory_dense', PACKAGE = 'beachmat.hdf5', file, name, forced_int, transpose)
}

load_into_memory_dense_as_sparse <- function(file, name, forced_int, transpose, cache_size, byrow) {
    .Call('_beachmat_hdf5_load_into_memory_dense_as_sparse', PACKAGE = 'beachmat.hdf5', file, name, forced_int, transpose, cache_size, byrow)
}

